config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    get '/expenses/stats' => 'expenses#stats', as: 'expenses_stats'
    get '/expenses/last_five' => 'expenses#last_five', as: 'expenses_last_five'
    get '/expenses/:id/jsontest' => 'expenses#jsontest'
    resources :expenses
    # resources :categories, only: [:show]
  end

  resources :categories, only: [:show]
  # resources :expenses

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy', as: 'logout'

  root to: "static#welcome"

  get '/auth/facebook/callback' => 'sessions#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnvelopeBudgetRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="wrapper">
      <% flash.each do |name, msg| %>
        <strong><%= content_tag :div, msg, class: "warning" %></strong>
      <% end %>

      <%= yield %>

      <% if logged_in? %>
        <div class="footer_buttons">
          <%=button_to "Your Account", user_path(current_user), :method => "get", :class => "big_button"%>
          <%=button_to "Edit Account", edit_user_path(current_user), :method => "get", :class => "big_button"%>
          <%=button_to "Your Expenses", user_expenses_path(current_user), :method => "get", :class => "big_button"%>
          <%=button_to "New Expense", new_user_expense_path(current_user), :method => "get", :class => "big_button"%>
          <%=button_to "Expense Stats", user_expenses_stats_path(current_user), :method => "get", :class => "big_button"%>
          <%=button_to "Logout", {controller: 'sessions', action: 'destroy', method: 'post'}, :class => "big_button"%>
        </div>
      <%end%>
      <footer class="branding">
        <small>&copy; 2018 <strong>EnvelopeBudgetRailsApp</strong></small>
      </footer>
    </div>
  </body>
</html>